version: "2"

run:
  go: "1.25"

linters:
  enable:
    - bodyclose
    - copyloopvar
    - dogsled
    - gosec
    - misspell
    - noctx
    - unparam
  settings:
    errcheck:
      check-type-assertions: true
      check-blank: false
    gosec:
      excludes:
        - G402
        - G107
        - G112
    govet:
      disable:
        - shadow
        - fieldalignment
      enable-all: true
    misspell:
      locale: US
    staticcheck:
      checks:
        - all
        - -SA1019
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - errcheck
          - gosec
        path: _test\.go
      - linters:
          - all
        path: zz_generated\.deepcopy\.go
    paths:
      - third_party$
      - builtin$
      - examples$

issues:
  max-issues-per-linter: 50
  max-same-issues: 5

formatters:
  enable:
    - gofmt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
