apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: scanpolicy-editor-role
  labels:
    app.kubernetes.io/name: clamav-operator
    app.kubernetes.io/component: rbac
rules:
- apiGroups: ["clamav.io"]
  resources: ["scanpolicies"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["clamav.io"]
  resources: ["scanpolicies/status"]
  verbs: ["get"]
