apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - bases/clamav.io_nodescans.yaml
  - bases/clamav.io_clusterscans.yaml
  - bases/clamav.io_scanpolicies.yaml
  - bases/clamav.io_scanschedules.yaml
  - bases/clamav.io_scancacheresources.yaml
